security:
  oauth2:
    client:
       clientId: a2ef8cc791710c0bba11
       clientSecret: ecaa3ca371c702bae0c58600705fd6dc91ead8d8
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
       tokenName: oauth_token
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: true 