#spring:
#  cloud:
#   gateway:
#    routes:
#      - id: movie-info-service
#        uri: lb://movie-info-service/
#        predicates:
#        - Path=/movies/**
#      - id: rating-data-service
#        uri: lb://rating-data-service/
#        predicates:
#        - Path=/ratingdata/**
zuul:
  sensitiveHeaders: Cookie,Set-Cookie
  routes:
    movie-info-service:
      path: /movies/**
      service-id: movie-info-service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie
    rating-data-service:
      service-id: rating-data-service
      path: /ratingdata/**
      sensitiveHeaders: Cookie,Set-Cookie
      strip-prefix: false     
security:
  oauth2:
    client:
       clientId: a2ef8cc791710c0bba11
       clientSecret: ecaa3ca371c702bae0c58600705fd6dc91ead8d8
       accessTokenUri: https://github.com/login/oauth/access_token
       userAuthorizationUri: https://github.com/login/oauth/authorize
       clientAuthenticationScheme: form
       tokenName: oauth_token
       responseType: code
    resource:
      user-info-uri: https://api.github.com/user
      prefer-token-info: true      